require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space

Metrics/BlockLength:
  IgnoredMethods:
    - describe

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false
